/* eslint-disable react-refresh/only-export-components */
export * from './login'
export * from './signup'
export * from './verfiyEmail'
// export * from './forgot'
// export * from './reset'
export * from './Home'
export * from './DashBoard'
export * from './faclilities'
export * from './reports'
export * from './forms/addAdmin'
export * from './forms/addWorker'
export * from './forms/addPatient' // same page will be used to create doctor
export * from './forms/addFacility'
export * from './forms/addReport'
export * from './pageNotFound'