/* eslint-disable react-refresh/only-export-components */
export * from './auth/login'
export * from './auth/signup'
export * from './Home'
export * from './DashBoard'
export * from './forms'
export * from './faclilities'
export * from './report/reportInfo'
export * from './report/ReportCardElement'
export * from './report/ReportsSection' 
export * from './forms/addAdmin'
export * from './forms/addWorker'
export * from './forms/addPatient' // same page will be used to create doctor
export * from './forms/addFacility'
export * from './forms/addReport'
export * from './pageNotFound'